config/routes.rb
Rails.application.routes.draw do
  # デバイス用
  devise_for :users
  resources :items
  root 'items#index'
  resources :products do
    collection do
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
      get 'search'
    end
    member do
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
    end

    resources :credit_cards, only:[:show] do
      member do
        post 'pay', to: 'credit_cards#pay'
        get 'done', to: 'credit_cards#done'
      end
    end
  end

  resources :credit_cards, only:[:new, :create, :index] do
    member do
      delete 'delete', to: 'credit_cards#delete'
    end
  end
  resources :users, only: :show
  resources :delivery_destinations, only:[:new, :create, :edit, :update]
end

app/models/credit_card.rb
class CreditCard < ApplicationRecord
  belongs_to :user
end

app/controllers/credit_cards_controller.rb
class CreditCardsController < ApplicationController
  
  require "payjp"

  before_action :authenticate_tosenbo

  def authenticate_tosenbo
    unless user_signed_in?
      redirect_to root_path
    end
  end

  def new
    @card = CreditCard.new
  end


  def create #payjpとCardのデータベース作成を実施します。
    Payjp.api_key = ENV['PAYJP_PRIVATE_KEY']
    if params['payjp-token'].blank?
      redirect_to action: "new"
    else
    customer = Payjp::Customer.create(
    card: params['payjp-token'],
    metadata: {user_id: current_user.id}
    ) #念の為metadataにuser_idを入れましたがなくてもOK
    @card = CreditCard.new(user_id: current_user.id, customer_id: customer.id, card_id: customer.default_card)
      if @card.save
        redirect_to root_path
      else
        redirect_to action: "new"
      end
    end
  end
  

  def show
    @product = Product.find(params[:id])
    card = CreditCard.find_by(user_id: current_user.id)
    #Cardテーブルは前回記事で作成、テーブルからpayjpの顧客IDを検索
    if @product.user_id == current_user.id || @product.trading_status
      redirect_to root_path
    elsif card.blank?
      #登録された情報がない場合にカード登録画面に移動
      redirect_to user_path(current_user.id)
    else
      Payjp.api_key = ENV['PAYJP_PRIVATE_KEY']
      #保管した顧客IDでpayjpから情報取得
      customer = Payjp::Customer.retrieve(card.customer_id)
      #保管したカードIDでpayjpから情報取得、カード情報表示のためインスタンス変数に代入
      @default_card_information = customer.cards.retrieve(card.card_id)
    end
  end


  def pay
    @product = Product.find(params[:id])
    card = CreditCard.find_by(user_id: current_user.id)
    Payjp.api_key = ENV['PAYJP_PRIVATE_KEY']
    Payjp::Charge.create(
    amount:  @product.price,
    customer: card.customer_id,
    currency: 'jpy',
    )
    @product[:trading_status] = 1
    @product.save
  redirect_to action: 'done'
  end

  def done
    @product = Product.find(params[:id])
  end


  def index 
    card = CreditCard.find_by(user_id: current_user.id)
    @card = card.id
    if card.blank?
      redirect_to action: "new" 
    else
      Payjp.api_key = ENV['PAYJP_PRIVATE_KEY']
      customer = Payjp::Customer.retrieve(card.customer_id)
      @default_card_information = customer.cards.retrieve(card.card_id)
    end
  end
  

  def delete #PayjpとCardデータベースを削除します
    card = CreditCard.find_by(user_id: current_user.id)
    if card.blank?
    else
      Payjp.api_key = ENV['PAYJP_PRIVATE_KEY']
      customer = Payjp::Customer.retrieve(card.customer_id)
      customer.delete
      card.delete
    end
      redirect_to action: "new"
  end


  private
  def credit_card_params
    params.permit('payjp-token',:product_id)
  end

  
end

app/views/credit_cards/done.html.haml
.Pay_main
  .Pay_main__box
    %p{class: "pay_question pay_content"} 購入が完了しました！
    %p{class: "product_name pay_content"}
      -# PC
      = @product.name
    %p{class: "product_price pay_content"}
      -# 10000円
      = "#{@product.price}円"
    .back_show
      = link_to "トップページに戻る", root_path

app/views/credit_cards/index.html.haml
.Pay_main
  .Pay_main__box
    .pay_content
      %label{class: "card_title"} 登録クレジットカード情報
      %br
      .card_info
        = "**** **** **** " + @default_card_information.last4
        %br
      .card_info
        - exp_month = @default_card_information.exp_month.to_s
        - exp_year = @default_card_information.exp_year.to_s.slice(2,3)
        = exp_month + " / " + exp_year
      .delete
        = form_tag(delete_credit_card_path(@card), method: :delete, id: 'charge-form',  name: "inputForm") do
          %input{ type: "hidden", name: "card_id", value: "" }
          %button{class: "delete__btn"} カードを削除する

app/views/credit_cards/new.html.haml
.content_main
  .content_box
    .content_title
      %h2 クレジットカード情報入力
    .credit-card
      .credit-card__inner
        = form_with model: @card, html: { name: "inputForm"}, local: true do |f|
          = f.label :カード番号, class: 'label'
          %span{class: "require"} 必須
          %br
          = f.text_field :card_number, type: 'text', class: 'input-number', placeholder: '半角数字のみ', maxlength: "16"
          .cards-expire
            = f.label :有効期限, class: 'label'
            %span{class: "require"} 必須
            %br
            .cards-expire__wrap
              = f.select :exp_month, [["01",1],["02",2],["03",3],["04",4],["05",5],["06",6],["07",7],["08",8],["09",9],["10",10],["11",11],["12",12]],{} , class: 'input-expire'
              %span.expire-text 月
              %br
            .cards-expire__wrap
              = f.select :exp_year, [["19",2019],["20",2020],["21",2021],["22",2022],["23",2023],["24",2024],["25",2025],["26",2026],["27",2027],["28",2028],["29",2029]],{} , class: 'input-expire'
              %span.expire-text 年
          .cards-expire
            = f.label :セキュリティコード, class: 'label'
            %span{class: "require"} 必須
            %br
            = f.text_field :cvc, type: 'text', class: 'input-number', placeholder: 'カード背面4桁もしくは3桁の番号', maxlength: "4"
          .content-bottom#card_token
            = f.submit '追加する', class: 'content-bottom--add-btn', id: 'token_submit'

app/views/credit_cards/show.html.haml
.Pay_main
  .Pay_main__box
    %p{class: "pay_question pay_content"} 購入を確定しますか？
    %p{class: "product_name pay_content"}
      = @product.name
    %p{class: "product_price pay_content"}
      = "#{@product.price}円"
    %br
    %p{class: "pay_title pay_content"} 支払い方法
    - if @default_card_information.blank?
      %br /
    - else
      -#以下カード情報を表示
      .card_infomation
        = "**** **** **** " + @default_card_information.last4
        - exp_month = @default_card_information.exp_month.to_s
        - exp_year = @default_card_information.exp_year.to_s.slice(2,3)
        = exp_month + " / " + exp_year
    %br
    = form_tag(action: :pay, method: :post) do
      %button{class: "pay_btn"} 購入する