config/routes.rb
Rails.application.routes.draw do
  # デバイス用
  devise_for :users
  resources :items
  root 'items#index'
  resources :products do
    collection do
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
      get 'search'
    end
    member do
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
    end

    resources :credit_cards, only:[:show] do
      member do
        post 'pay', to: 'credit_cards#pay'
        get 'done', to: 'credit_cards#done'
      end
    end
  end

  resources :credit_cards, only:[:new, :create, :index] do
    member do
      delete 'delete', to: 'credit_cards#delete'
    end
  end
  resources :users, only: :show
  resources :delivery_destinations, only:[:new, :create, :edit, :update]
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
        :recoverable, :rememberable, :validatable

# # ここから追記
  has_many :products, dependent: :destroy
  has_one :delivery_destination, dependent: :destroy
  has_one :credit_card, dependent: :destroy

# バリデーションの追加
  validates :nickname, :family_name, :first_name, :family_name_kana, :first_name_kana, :birth_day, :password, :password_confirmation, :email, presence: true
  validates :nickname, :family_name, :first_name, :family_name_kana, :first_name_kana, length: { maximum: 15 }
  validates :nickname, uniqueness: true
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to root_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if current_user.update(user_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  def show
    @user = User.find(params[:id])
    @nickname = current_user.nickname
    @products = current_user.products
    @delivery = current_user.delivery_destination
    unless user_signed_in? && @user.id == current_user.id
      redirect_to root_path
    else
      render :show
    end
  end

  private

  def user_params
    params.require(:user).permit(:nickname, :user_image, :profile, :family_name, :first_name, :family_name_kana, :first_name_kana, :birth_day)
  end

end

app/views/users/show.html.haml
%link{:href => "show.scss", :rel => "stylesheet"}/
%body
  .MainWrapper
    .MainContainer
      .Information
        マイページ
      .SecondaryContent
        .userName
          = @nickname
      .userBox
        .userBox__content
          .deliveryBar
            %p 配送先住所
            - if @delivery == nil
              = link_to "配送先住所の登録", new_delivery_destination_path, class: 'deliveryInfo'
            - else
              = link_to "配送先住所の編集", edit_delivery_destination_path(@delivery), class: 'deliveryInfo'
          .addressBar
            - unless @delivery == nil
              .userBox__content--info
                = @delivery.prefecture_i18n
                = @delivery.city
                = @delivery.address
                = @delivery.buiding_name
        .userBox__content
          出品商品履歴
          - @products.each do |product|
            .productBar
              .productBar__name
                = product.name
              .productBar__info
                = link_to "詳細", product_path(product.id)
      .cardBox
        .cardPages
          = link_to "クレジットカードの登録", new_credit_card_path, data: {"turbolinks" => false}
        .cardPages
          = link_to "クレジットカードの削除", credit_cards_path