config/routes.rb
Rails.application.routes.draw do
  # デバイス用
  devise_for :users
  resources :items
  root 'items#index'
  resources :products do
    collection do
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
      get 'search'
    end
    member do
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
    end

    resources :credit_cards, only:[:show] do
      member do
        post 'pay', to: 'credit_cards#pay'
        get 'done', to: 'credit_cards#done'
      end
    end
  end

  resources :credit_cards, only:[:new, :create, :index] do
    member do
      delete 'delete', to: 'credit_cards#delete'
    end
  end
  resources :users, only: :show
  resources :delivery_destinations, only:[:new, :create, :edit, :update]
end

app/models/product.rb
class Product < ApplicationRecord

    has_many :product_imgs, dependent: :destroy
    belongs_to :category
    has_many :brands, dependent: :destroy
    belongs_to :user
    accepts_nested_attributes_for :product_imgs, limit: 10, allow_destroy: true
    accepts_nested_attributes_for :brands, allow_destroy: true

    validates :name, :price, :description, :condition, :size, :shipping_cost, :shipping_days, :prefecture, :user_id, :category_id, :product_imgs ,presence: true
    # validates :trading_status,  presence: true
    validates :name, length: { maximum: 40 }
    validates :description, length: {maximum: 1000}
    validates :price, numericality: { only_integer: true,greater_than_or_equal_to: 300, less_than_or_equal_to: 9999999 }
    validates :condition, :shipping_cost, :shipping_days, :prefecture, exclusion: { in: ["---"] }
    validates :category_id, presence: true, exclusion: { in: 1..158 }

    enum condition:{
        '---':           0, #---
        unused:          1, #新品、未使用
        nearly_unused:   2, #未使用に近い
        not_injured:     3, #目立った傷や汚れなし
        bit_injured:     4, #やや傷や汚れあり
        injured:         5, #傷や汚れあり
        bad:             6,  #全体的に状態が悪い
    },_prefix: true

    enum shipping_cost:{
        '---':                      0,  #---
        shipping_fee_on_shipper:    1,  #送料込み（出品者負担）
        shipping_fee_on_receiver:   2,  #着払い（購入者負担）
    },_prefix: true

    enum shipping_days:{
        '---':      0,  #---
        days1_2:    1,  #
        days2_3:    2,  #2日~3日で発送
        days4_7:    3,  #4日~7日で発送
    },_prefix: true

    enum prefecture:{
        '---':       0,
        hokkaido:    1,
        aomori:      2,
        iwate:       3,
        miyagi:      4,
        akita:       5,
        yamagata:    6,
        fukushima:   7,
        ibaraki:     8,
        tochigi:     9,
        gunma:      10,
        saitama:    11,
        chiba:      12,
        tokyo:      13,
        kanagawa:   14,
        niigata:    15,
        toyama:     16,
        ishikawa:   17,
        fukui:      18,
        yamanashi:  19,
        nagano:     20,
        gifu:       21,
        shizuoka:   22,
        aichi:      23,
        mie:        24,
        shiga:      25,
        kyoto:      26,
        osaka:      27,
        hyogo:      28,
        nara:       29,
        wakayama:   30,
        tottori:    31,
        shimane:    32,
        okayama:    33,
        hiroshima:  34,
        yamaguchi:  35,
        tokushima:  36,
        kagawa:     37,
        ehime:      38,
        kochi:      39,
        fukuoka:    40,
        saga:       41,
        nagasaki:   42,
        kumamoto:   43,
        oita:       44,
        miyazaki:   45,
        kagoshima:  46,
        okinawa:    47
  }

    def previous
      Product.where("id < ?", self.id).order("id DESC").first
    end

    def next
      Product.where("id > ?", self.id).order("id ASC").first
    end

  end

# for check

app/controllers/products_controller.rb
class ProductsController < ApplicationController

before_action :set_category, only: [:new, :edit, :create, :update, :destroy]
before_action :set_product, only: [:show, :edit, :update, :destroy, :purchase, :buy, :set_category]
before_action :set_edit_category, only: [:edit]

    def index
        @products = Product.all.order("id DESC").limit(10)
        @products = Product.includes(:product_imgs).order('created_at DESC')

    end

    def new
        @product = Product.new
        @product.product_imgs.build
        @product.brands.build
        @parent = Category.where(id: 1..13)
        unless user_signed_in?
            flash[:alert] = "ログインしていません"
            redirect_to user_session_path
        else
            render :new
        end

    end

    def create
        @product = Product.new(product_params)
        if @product.save!
            flash[:notice] = "出品が完了しました。"
            redirect_to root_path
        else
            flash[:alert] = "出品に失敗しました。"
            render :new
        end
    end

    def show
        @product_img = @product.product_imgs.first
        @brand = Brand.find(@product.id)
    end

    def edit
        unless user_signed_in? && @product.user_id == current_user.id
            redirect_to product_path(@product)
        else
            render :edit
        end
    end

    def update
        if @product.user_id == current_user.id && @product.update(product_params)
            flash[:notice] = "更新が完了しました。"
            redirect_to product_path(@product)
        else
            render :edit
        end
    end

    def destroy
        if @product.user_id == current_user.id && @product.destroy
            flash[:alert] = "商品は削除されました。"
            redirect_to root_path
        else
            redirect_to product_path(@product.id)
        end
    end

    def search
      @products = Product.search(params[:keyword])
    end

    #jsonで親の名前で検索し、紐づく子カテゴリーの配列を取得
    def get_category_children
        @category_children = Category.find(params[:parent_id]).children
    end

    #jsonで子カテゴリーに紐づく孫カテゴリーの配列を取得
    def get_category_grandchildren
        @category_grandchildren = Category.find(params[:child_id]).children
    end

    #親カテゴリー
    def set_category
        @category_parent_array = Category.where(ancestry: nil)
    end

    #編集画面用のカテゴリー
    def set_edit_category
    @category_children_array = @product.category.parent.siblings
    @category_grandchildren_array = @product.category.siblings
    end

    private

    def set_product
        @product = Product.find(params[:id])
    end

    def product_params
        params.require(:product)
            .permit(:name, :price, :description, :condition,
                :size, :shipping_cost, :shipping_days,
                :prefecture, :trading_status,
                :category_id,
                product_imgs_attributes: [:image, :image_cache,:_destroy, :id],
                brands_attributes: [:name, :id]
            )
            .merge(user_id: current_user.id)
    end

end

app/views/products/edit.html.haml
.main
  .edit-main
    .contentRight
      .topContent
        = form_with model: @product do |f|
          .uploader-info
            .form-field
              = f.label :name, "出品画像", class: "label-text"
              %span{class: "require"} 必須
              .information 最大10枚までアップロードできます。
              %ul
                //JSで挿入したhtmlと同じ形 each文でのプレビュー表示
              - @product.product_imgs.each_with_index do |image, index|
                .preview-box
                  .upper-box
                    = image_tag image.image.url(:thumb), alt: "preview",class: "img2"
                - if index != 0
                  .lower-box
                    .delete-box{data: {index: index}}
                      .delete-btn
                        %span 削除
            .label-content
              //プレビューの数に合わせてforオプションを指定
              = f.label :"imgs_attributes_#{@product.product_imgs.length}_image", class: "label-box", id: "label-box--#{@product.product_imgs.length}" do
                %pre.label-box__text-visible クリックしてファイルをアップロード
            .hidden-content
              - (count = 0)
              = f.fields_for :product_imgs do |image|
                //プレビューが出ている分のfile_fieldとdelete用のチェックボックスを設置
                = image.file_field :image, class: "hidden-field"
                = "#{count += 1}個目の画像編集用フォームです"
                = image.check_box:_destroy, class: "hidden-checkbox"
                //10個のfile_fieldを準備するに当たって、足りない分を表示
              - @product.product_imgs.length.upto(9) do |i|
                %input{name: "product[product_imgs_attributes][#{i}][image]", id: "product_imgs_attributes_#{i}_image", class:"hidden-field", type:"file"}
                #{i + 1}個目の画像編集用フォームです
          .product-info
            .form-field
              = f.label :name, "商品名", class: "label-text"
              %span{class: "require"} 必須
              = f.text_field :name, placeholder: "商品名 (必須40文字まで)", id: "productr_name", class: "textform_bl"
            .form-field
              = f.label :name, "商品説明", class: "label-text"
              %span{class: "require"} 必須
              = f.text_area :description, size: "73x7", placeholder: "商品の説明（必須1,000文字以内 (色、素材、重さ、定価、注意点など)", id: "product_introduction", class: "textarea_bl"
          .product-description
            %h2 商品の詳細
            .form-field
              = f.label :name, "カテゴリー", class: "label-text"
              %span{class: "require"} 必須
            .categoly_form#partent_box
              = f.select :category_id, options_for_select( @category_parent_array.map{|c| [c[:name], c[:id]]}, selected: @product.category.parent.parent.id),{}, { class: "parent_category_box selectform_bl", id: "parent_category"}
            #children_box
              = f.select :category_id, options_for_select( @category_children_array.map{|c| [c[:name], c[:id]]}, selected: @product.category.parent.parent.id),{}, { class: "children_category_box selectform_bl", id: "children_category"}
            #grandchildren_box
              = f.select :category_id, options_for_select( @category_grandchildren_array.map{|c| [c[:name], c[:id]]}, selected: @product.category),{}, { class: "grandchildren_category_box selectform_bl", id: "grandchildren_category"}
            .form-field
              = f.label :name, "商品サイズ", class: "label-text"
              %span{class: "require"} 必須
              = f.text_field :size, placeholder:"サイズを入力してください", class: "textform_bl"
            .form-field
              = f.label :name, "ブランド", class: "label-text"
              = f.fields_for :brands do |b|
                = b.text_field :name, class: "textform_bl"
            .form-field
              = f.label :name, "商品の状態", class: "label-text"
              %span{class: "require"} 必須
              = f.select :condition, Product.conditions.keys.map {|k| [I18n.t("enums.product.condition.#{k}"), k]}, {}, { class: "selectform_bl"}
          .shipping-info
            %h2 配送について
            .form-field
              = f.label :name, "配送料の負担", class: "label-text"
              %span{class: "require"} 必須
              = f.select :shipping_cost, Product.shipping_costs.keys.map {|k| [I18n.t("enums.product.shipping_cost.#{k}"), k]}, {}, { class: "selectform_bl"}
            .form-field
              = f.label :name, "発送元の地域", class: "label-text"
              %span{class: "require"} 必須
              = f.select :prefecture, Product.prefectures.keys.map {|k| [I18n.t("enums.product.prefecture.#{k}"), k]}, {}, { class: "selectform_bl"}
            .form-field
              = f.label :name, "発送までの日数", class: "label-text"
              %span{class: "require"} 必須
              = f.select :shipping_days,Product.shipping_days.keys.map {|k| [I18n.t("enums.product.shipping_days.#{k}"), k]},{}, { class: "selectform_bl"}
          .price-info
            %h2 価格（¥300〜9,999,999）
            .form-field
              = f.label :name, "販売価格", class: "label-text"
              %span{class: "require"} 必須
              = f.text_field :price, id: "pricebox", placeholder: "例） 300", class: "textform_bl"
            .price-info__calc
              販売手数料（10%）
          .submit-field
            .btn-box
              = f.submit :変更する,id: "btn", class: "edit-btn"
            .btn-box
              = link_to "もどる", :back, class: "back-btn"
          .notification
            .notification__message
              = link_to("禁止されている出品", "＃")
              、
              = link_to("行為", "＃")
              を必ずご確認ください。
              %br
              またブランド品でシリアルナンバー等がある場合はご記載ください。
              %br
              = link_to("偽ブランドの販売", "＃")
              は犯罪であり処罰される可能性があります。
              %br
              また、出品をもちまして
              = link_to("加盟店規約", "＃")
              に同意したことになります。
= render "layouts/appBanner"

app/views/products/new.html.haml
.main
  .exhibit-main
    .contentRight
      .topContent
        = form_with model: @product, url:products_path do |f|
          .uploader-info
            .form-field
              = f.label :name, "出品画像", class: "label-text"
              %span{class: "require"} 必須
              .infomation 最大10枚までアップロードできます
              .img_zone
              = f.fields_for :product_imgs do |image|
                .dropzone-container.clearfix
                  #preview
                  .dropzone-area
                    = image.label :image, class: "dropzone_box", for: "upload-image" do
                      .input_area
                        = fa_icon 'camera'
                        = image.file_field :image, id: "upload-image", class: "upload-image", 'data-image': 0
                      %p ドラッグアンドドロップ
                  #preview2
                  .dropzone-area2
                    = image.label :image, multiple: true, class: "dropzone_box", for: "upload-image" do
                      %p またはクリックしてファイルをアップロード
          .product-info
            .form-field
              = f.label :name, "商品名", class: "label-text"
              %span{class: "require"} 必須
              = f.text_field :name, placeholder: "商品名 (必須40文字まで)", id: "productr_name", class: "textform_bl"
            .form-field
              = f.label :name, "商品説明", class: "label-text"
              %span{class: "require"} 必須
              = f.text_area :description, size: "73x7", placeholder: "商品の説明（必須1,000文字以内 (色、素材、重さ、定価、注意点など)", id: "product_introduction", class: "textarea_bl"
          .product-description
            %h2 商品の詳細
            .form-field
              = f.label :name, "カテゴリー", class: "label-text"
              %span{class: "require"} 必須
            .categoly_form#partent_box
              = f.select :category_id, options_for_select( @category_parent_array.map{|c| [c[:name], c[:id]]}),{include_blank: "選択してください"}, { class: "parent_category_box selectform_bl", id: "parent_category"}
            #children_box
            #grandchildren_box
            .form-field
              = f.label :name, "商品サイズ", class: "label-text"
              %span{class: "require"} 必須
              = f.text_field :size, placeholder:"サイズを入力してください", class: "textform_bl"
            .form-field
              = f.label :name, "ブランド", class: "label-text"
              = f.fields_for :brands do |b|
                = b.text_field :name, class: "textform_bl"
            .form-field
              = f.label :name, "商品の状態", class: "label-text"
              %span{class: "require"} 必須
              = f.select :condition, Product.conditions.keys.map {|k| [I18n.t("enums.product.condition.#{k}"), k]}, {}, { class: "selectform_bl"}
          .shipping-info
            %h2 配送について
            .form-field
              = f.label :name, "配送料の負担", class: "label-text"
              %span{class: "require"} 必須
              = f.select :shipping_cost, Product.shipping_costs.keys.map {|k| [I18n.t("enums.product.shipping_cost.#{k}"), k]}, {}, { class: "selectform_bl"}
            .form-field
              = f.label :name, "発送元の地域", class: "label-text"
              %span{class: "require"} 必須
              = f.select :prefecture, Product.prefectures.keys.map {|k| [I18n.t("enums.product.prefecture.#{k}"), k]}, {}, { class: "selectform_bl"}
            .form-field
              = f.label :name, "発送までの日数", class: "label-text"
              %span{class: "require"} 必須
              = f.select :shipping_days,Product.shipping_days.keys.map {|k| [I18n.t("enums.product.shipping_days.#{k}"), k]},{}, { class: "selectform_bl"}
          .price-info
            %h2 価格（¥300〜9,999,999）
            .form-field
              = f.label :name, "販売価格", class: "label-text"
              %span{class: "require"} 必須
              = f.text_field :price, id: "pricebox", placeholder: "例） 300", class: "textform_bl"
            .price-info__calc
              販売手数料（10%）
          .submit-field
            .btn-box
              = f.submit :出品する,id: "btn", class: "exhibit-btn", data: {"turbolinks"=>false}
            .btn-box
              = link_to "もどる", root_path, class: "back-btn"
          .notification
            .notification__message
              = link_to("禁止されている出品", "＃")
              、
              = link_to("行為", "＃")
              を必ずご確認ください。
              %br
              またブランド品でシリアルナンバー等がある場合はご記載ください。
              %br
              = link_to("偽ブランドの販売", "＃")
              は犯罪であり処罰される可能性があります。
              %br
              また、出品をもちまして
              = link_to("加盟店規約", "＃")
              に同意したことになります。
= render "layouts/appBanner"

app/views/products/search.html.haml
test

app/views/products/show.html.haml
.main
  .showMain
    .contentRight
      .topContent
        .itemBox
          %h2.itemBox__name
            = @product.name
          .itemBox__body
            %ul
              %li
                = image_tag @product_img.image_url
                %ul
                  - @product.product_imgs.each do |product_img|
                    %li
                      = image_tag product_img.image_url
          .itemBox__price
            %span
              = "#{@product.price}円"
            .itemBox__price-detail
              %span
                (税込)
              %span
                送料込み
          .itemDetail
            = @product.description
          .table
            %table
              %tbody
                %tr
                  %th 出品者
                  %td
                    = @product.user.nickname
                %tr
                  %th カテゴリー
                  %td
                    = link_to "#{@product.category.parent.parent.name}", root_path
                    %br
                    = link_to "#{@product.category.parent.name}", root_path
                    %br
                    = link_to "#{@product.category.name}", root_path
                    %br
                %tr
                  %th ブランド
                  %td
                    = @brand.name
                %tr
                  %th 商品のサイズ
                  %td
                    = @product.size
                %trv
                  %th 商品の状態
                  %td
                    = @product.condition_i18n
                %tr
                  %th 配送料の負担
                  %td
                    = @product.shipping_cost_i18n
                %tr
                  %th 発送元の地域
                  %td
                    = @product.prefecture_i18n
                %tr
                  %th 発送日の目安
                  %td
                    = @product.shipping_days_i18n
      %ul.links
        %li
          - if @product.previous.present?
            = link_to product_path(@product.previous) do
              = "前の商品"
        %li
          - if @product.next.present?
            = link_to product_path(@product.next) do
              = "次の商品"
      - if @product.trading_status
        .buy_box
          = "この商品は売り切れました。"
      - elsif user_signed_in? && current_user.id != @product.user_id
        .buy_box
          = link_to "購入する", product_credit_card_path(@product.id), class: "buy_btn"
      - elsif user_signed_in? && current_user.id == @product.user_id
        .edit_box
          = link_to "出品情報を編集する", edit_product_path, class: "edit_btn"
        .edit_box
          = link_to '削除', product_path(@product.id), method: :delete, class: "delete_btn"
      - else
        .buy_box
          = "商品を購入するにはユーザーログインが必要です。"

= render "layouts/appBanner"