config/routes.rb
Rails.application.routes.draw do
  # デバイス用
  devise_for :users
  resources :items
  root 'items#index'
  resources :products do
    collection do
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
      get 'search'
    end
    member do
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
    end

    resources :credit_cards, only:[:show] do
      member do
        post 'pay', to: 'credit_cards#pay'
        get 'done', to: 'credit_cards#done'
      end
    end
  end

  resources :credit_cards, only:[:new, :create, :index] do
    member do
      delete 'delete', to: 'credit_cards#delete'
    end
  end
  resources :users, only: :show
  resources :delivery_destinations, only:[:new, :create, :edit, :update]
end

app/views/layouts/_appBanner.html.haml
%aside.appBanner
  .inner
    %h2.inner__title だれでもかんたん、人生を変えるフリマアプリ
    %p.inner__text 今すぐ無料ダウンロード！
    .inner__icon
      = link_to image_tag("icon/icon_apple.png", class:"bannerBtn")
      = link_to image_tag("icon/icon_google.png", class:"bannerBtn")

app/views/layouts/_footer.html.haml
.footer
  %ul.contents
    %li.content2
      %h2.content2__head FURIMAについて
      %ul
        %li
          = link_to "会社概要（運営会社）", "#", class: "footerLink"
        %li
          = link_to "プライバシーポリシー", "#", class: "footerLink"
        %li
          = link_to "FURIMA利用規約", "#", class: "footerLink"
        %li
          = link_to "ポイントに関する特約", "#", class: "footerLink"
    %li.content2
      %h2.content2__head FURIMAを見る
      %ul
        %li
          = link_to "カテゴリー一覧", "#", class: "footerLink"
        %li
          = link_to "ブランド一覧", "#", class: "footerLink"
    %li.content2
      %h2.content2__head ヘルプ＆ガイド
      %ul
        %li
          = link_to "FURIMAガイド", "#", class: "footerLink"
        %li
          = link_to "FURIMAロゴ利用ガイドライン", "#", class: "footerLink"
        %li
          = link_to "お知らせ", "#", class: "footerLink"
  .footer__logo
    = link_to "/" do
      = image_tag 'logo/logo-white.png', alt: 'ロゴ'
  %p.copyright © FURIMA
= link_to new_product_path do
  .purchaseBtn
    %span.purchaseBtn__text 出品する
    = image_tag 'icon/icon_camera.png', alt: '出品ボタン', class: 'purchaseBtn__icon'

app/views/layouts/_header.html.haml
.pcHeader
  .headerInner
    .mainHeader
      .icon
        = link_to root_path do
          = image_tag 'logo/logo.png', alt: 'ロゴ'
      .searchBox
        = form_with url: search_products_path, method: :get  do |f|
          = f.text_field :keyword, class:'search-form', placeholder: "商品を検索する"
          = f.submit "検索", class: 'search-btn'
          -# .searchBox__icon
          -#   = image_tag '', alt: '検索'
      .resultLists
    .nav
      .listsLeft
        .listsLeft__item.listsLeft__item--first
          = link_to "カテゴリー", "", class: "categoryBtn"
          .categoryField.displayNone
            .parentsList
              - @parents.each do |parent|
                .parentsList--item
                  = link_to "#{parent.name}", item_path(parent), class: "parentCategory", id: "#{parent.id}"
            .childrenList
              .childrenList--item
            .grandChildrenList
              .grandChildrenList--item
        .listsLeft__item
          = link_to "ブランド", "#", class: "brandBtn"
      .listsRight
        - if user_signed_in?
          .listsRight__item.listsRight__item--logout
          = link_to "マイページ", user_path(current_user), class: "right_contents"
          = link_to "ログアウト", destroy_user_session_path, method: :delete, class: "right_contents"
        - else
          .listsRight__item.listsRight__item--login
            = link_to "ログイン", new_user_session_path, method: :get
          .listsRight__item.listsRight__item--new
            = link_to "新規会員登録", new_user_registration_path, method: :get

app/views/layouts/_no-purchase-footer.html.haml
.footer
  %ul.contents
    %li.content2
      %h2.content2__head FURIMAについて
      %ul
        %li
          = link_to "会社概要（運営会社）", "#", class: "footerLink"
        %li
          = link_to "プライバシーポリシー", "#", class: "footerLink"
        %li
          = link_to "FURIMA利用規約", "#", class: "footerLink"
        %li
          = link_to "ポイントに関する特約", "#", class: "footerLink"
    %li.content2
      %h2.content2__head FURIMAを見る
      %ul
        %li
          = link_to "カテゴリー一覧", "#", class: "footerLink"
        %li
          = link_to "ブランド一覧", "#", class: "footerLink"
    %li.content2
      %h2.content2__head ヘルプ＆ガイド
      %ul
        %li
          = link_to "FURIMAガイド", "#", class: "footerLink"
        %li
          = link_to "FURIMAロゴ利用ガイドライン", "#", class: "footerLink"
        %li
          = link_to "お知らせ", "#", class: "footerLink"
  .footer__logo
    = link_to "/" do
      = image_tag 'logo/logo-white.png', alt: 'ロゴ'
  %p.copyright © FURIMA

app/views/layouts/_notifications.html.haml
.Notification
  - flash.each do |key, value|
    = content_tag :div, value, class: key

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title FleamarketSample80b
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application'
    -# = javascript_pack_tag 'application'（webpackerを使うならこれ。JSファイル全てをpacksディレクトリに移動jQuelyが使えない）
    %script{src: "https://js.pay.jp/v1/", type: "text/javascript"}
  %body
    = render 'layouts/notifications'
    = render "layouts/header"
    = yield
    = render "layouts/footer"